spring:
  redis:
    host: 192.168.242.136
    port: 6379
    password: 123456

  datasource:
    url: jdbc:mysql://192.168.242.136:3306/redis_quickstart?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.example.redisquickstart.mapper: debug